"""Launch Gazebo (gz sim) with an SDF world generated by map2sdf."""

import os

from ament_index_python.packages import get_package_share_directory

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration


def generate_launch_description():
    """Start gz sim with the world given by the ``world`` launch argument."""
    world = LaunchConfiguration('world')
    gz_extra_args = LaunchConfiguration('gz_extra_args')

    gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(
            get_package_share_directory('ros_gz_sim'),
            'launch', 'gz_sim.launch.py')),
        launch_arguments={'gz_args': [gz_extra_args, ' -r ', world]}.items())

    return LaunchDescription([
        DeclareLaunchArgument(
            'world',
            description='path to the SDF world file generated by map2sdf'),
        DeclareLaunchArgument(
            'gz_extra_args', default_value='',
            description="extra gz sim arguments, e.g. '-s' for headless"),
        gz_sim,
    ])
